# Book settings
title: Support for Estimating Socio-Economic Impacts of Turkiye-Syria Earthquake
author: World Bank Data Lab
logo: docs/images/logo.png

repository:
    url: https://github.com/Holly-Transport/Turkiye_Earthquake
    branch: main

html:
    home_page_in_navbar: false
    extra_navbar: ""
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://Holly-Transport/Turkiye_Earthquake

only_build_toc_files: true
